# Generated by Django 2.0 on 2017-12-08 17:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('calories_burn', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kcal', models.FloatField(null=True)),
                ('total_carbs', models.FloatField(null=True)),
                ('total_proteins', models.FloatField(null=True)),
                ('total_fat', models.FloatField(null=True)),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Diary')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kcal', models.FloatField(null=True)),
                ('carbs', models.FloatField(null=True)),
                ('proteins', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('daily_kcal', models.FloatField(null=True)),
                ('daily_carbs', models.FloatField(null=True)),
                ('daily_fat', models.FloatField(null=True)),
                ('daily_proteins', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_app.Meal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Product'),
        ),
        migrations.AddField(
            model_name='diary',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='diary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Diary'),
        ),
        migrations.AddField(
            model_name='activity',
            name='discipline_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_app.Discipline'),
        ),
    ]
