# Generated by Django 2.0 on 2017-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0003_auto_20171208_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
