# Generated by Django 2.0 on 2017-12-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0004_auto_20171208_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='diary_id',
            new_name='diary',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='diary_id',
            new_name='diary',
        ),
        migrations.RenameField(
            model_name='mealtype',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='user_id',
            new_name='user',
        ),
    ]
