# Generated by Django 2.0 on 2017-12-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0005_auto_20171210_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='discipline_id',
            new_name='discipline',
        ),
    ]
