# Generated by Django 2.0 on 2017-12-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0007_auto_20171217_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='mealtype',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diet_app.MealType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealtype',
            name='diary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diet_app.Diary'),
            preserve_default=False,
        ),
    ]
