# Generated by Django 2.0 on 2017-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0008_auto_20171224_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
